export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_STAFFS = 'ADD_STAFF';

export const DEPARTMENTS_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';

export const SALARY_LOADING = 'SALARY_LOADING';
export const SALARY_FAILED = 'SALARY_FAILED';
export const ADD_SALARY = 'ADD_SALARY';

